### PR TITLE
PDS4 Information Model Release 1.19.0.0

### PR DESCRIPTION
**Pull request by pds-ops**
Automated tagging of repo for nominal release of sub-model for PDS4 Release 1.19.0.0

### CODE REVIEW

**Comment by jordanpadams** [comment]
@acraugh are we are go for merging this and tagging it with this release?

**Comment by acraugh** [comment]
I honestly haven't had time to think about the spectral dictionary. I'll go
look at the logs now.

-Anne.

**Comment by acraugh** [comment]
I'm seeing some regression test failure messages that look like Validate
got better rather than anything going wrong in the build. I'll file an
issue to remind me to fix that, but the release can go ahead.

Thanks!

-Anne.

**Comment by acraugh** [comment]
OK, I give up - how do I indicate that a review has happened so the block
can be removed?

-Anne.

**Review by acraugh — APPROVED** [review]
Figured it out

**Review by jordanpadams — APPROVED** [review]

**Pull request merged**
